# WAF 指纹特征库（数据驱动，架构与 fingerprint_features.py 一致）
# 新增 WAF 只需在此追加一条特征数据，fingerprint 模块自动识别。
#
# 特征类型说明：
#   headers     : 响应头中可能出现的 WAF 特征（键或值包含关键字即命中）
#   body        : 响应体中可能出现的 WAF 拦截页关键字
#   cookie      : Set-Cookie 中的 WAF 特征
#   status      : WAF 拦截时的典型状态码（如 403/406）
#   block_signatures: WAF 拦截响应的典型特征（用于区分"真 SAFE"和"被拦假 SAFE"）
#   recommended_strategies: D7 推荐绕过策略 ID 列表（按优先级排序）
# 命中任一特征即判定存在该 WAF。

WAF_FEATURES = {
    "cloudflare": {
        "display": "Cloudflare",
        "headers": ["cf-ray", "__cfduid", "CF-Cache-Status", "cf-request-id"],
        "body": ["Cloudflare", "cf-browser-verification", "Checking your browser"],
        "cookie": ["__cfduid", "__cf_bm"],
        "status": [403, 503],
        "bypass_hint": "尝试寻找源服务器真实 IP（Censys/Shodan/SSL证书），绕过 CDN 直连源站",
        "block_signatures": ["Attention Required!", "cloudflare", "cf-ray", "Ray ID:", "Please enable cookies"],
        "recommended_strategies": ["BP-CF-1", "BP-CF-2", "BP-CF-3"],
    },
    "aliyun_waf": {
        "display": "阿里云 WAF",
        "headers": ["aliyun-waf", "aliyun-waf-", "X-WAF-Action"],
        "body": ["aliyunwaf", "阿里云 Web 应用防火墙", "request blocked by alibaba cloud waf"],
        "cookie": ["aliyungf_tc"],
        "status": [405],
        "bypass_hint": "尝试分块传输编码绕过，或使用 CDN 节点 IP 池",
        "block_signatures": ["aliyunwaf", "阿里云Web应用防火墙", "request blocked", "405 Not Allowed"],
        "recommended_strategies": ["BP-ALI-1", "BP-ALI-2", "BP-ALI-3"],
    },
    "safedog": {
        "display": "安全狗",
        "headers": ["safedog", "Safedog"],
        "body": ["安全狗", "safedog", "SafeDog", "您的请求已被拦截"],
        "cookie": ["safedog"],
        "status": [403],
        "bypass_hint": "尝试内联注释变形 SQL 语句，或使用延时绕过",
        "block_signatures": ["安全狗", "safedog", "您的请求已被拦截", "WAF"],
        "recommended_strategies": ["BP-SD-1", "BP-SD-2", "BP-SD-3"],
    },
    "chaitin": {
        "display": "长亭 SafeLine",
        "headers": ["SL-", "safeline"],
        "body": ["长亭", "SafeLine", "safeline", "雷池"],
        "cookie": [],
        "status": [403],
        "bypass_hint": "SafeLine 对语义分析较强，尝试编码变形或协议层绕过",
        "block_signatures": ["长亭", "SafeLine", "safeline", "雷池", "请求被拦截"],
        "recommended_strategies": ["BP-CP-1", "BP-CP-2", "BP-CP-3"],
    },
    "baidu_waf": {
        "display": "百度云 WAF",
        "headers": ["yunjiasu", "Yunjiasu"],
        "body": ["yunjiasu", "百度云加速"],
        "cookie": ["yunjiasu"],
        "status": [403],
        "bypass_hint": "尝试源站 IP 绕过，或使用 WebSocket 协议绕过",
        "block_signatures": ["yunjiasu", "百度云加速", "访问被拒绝"],
        "recommended_strategies": ["BP-BD-1", "BP-BD-2", "BP-BD-3"],
    },
    "tencent_waf": {
        "display": "腾讯云 WAF",
        "headers": ["tencent-waf", "T-Sec-WAF"],
        "body": ["腾讯云 WAF", "tencent cloud waf"],
        "cookie": [],
        "status": [403],
        "bypass_hint": "尝试参数污染或分块传输绕过",
        "block_signatures": ["腾讯云WAF", "tencent cloud waf", "请求被拦截"],
        "recommended_strategies": ["BP-TX-1", "BP-TX-2", "BP-TX-3"],
    },
    "knownsec": {
        "display": "知道创宇 WAF",
        "headers": ["knownsec"],
        "body": ["knownsec", "知道创宇", "创宇盾"],
        "cookie": [],
        "status": [403],
        "bypass_hint": "尝试 HTTP/2 或 WebSocket 协议绕过",
        "block_signatures": ["knownsec", "知道创宇", "创宇盾", "请求被拦截"],
        "recommended_strategies": ["BP-KS-1", "BP-KS-2", "BP-KS-3"],
    },
    "modsecurity": {
        "display": "ModSecurity",
        "headers": ["Mod_Security", "mod_security"],
        "body": ["ModSecurity", "mod_security", "This error was generated by Mod_Security"],
        "cookie": [],
        "status": [403, 406],
        "bypass_hint": "尝试编码绕过或分块传输绕过，ModSecurity 对 SQLi 规则较敏感",
        "block_signatures": ["ModSecurity", "mod_security", "Mod_Security", "Not Acceptable", "OWASP"],
        "recommended_strategies": ["BP-MS-1", "BP-MS-2", "BP-MS-3"],
    },
    # D15：AWS WAF
    "aws_waf": {
        "display": "AWS WAF",
        "headers": ["x-amzn-waf", "x-amz-cf-id", "X-Amzn-WAF-Action"],
        "body": ["AWS WAF", "AWSWAF", "request blocked by AWS WAF"],
        "cookie": [],
        "status": [403],
        "bypass_hint": "尝试源站 IP 绕过或 HTTP 头变形",
        "block_signatures": ["AWS WAF", "AWSWAF", "request blocked"],
        "recommended_strategies": ["BP-AW-1", "BP-AW-2", "BP-AW-3"],
    },
    # D15：F5 BIG-IP ASM
    "f5_asm": {
        "display": "F5 BIG-IP ASM",
        "headers": ["BigIPServer", "F5", "X-WA-Info", "TS01"],
        "body": ["BIG-IP", "ASM", "F5", "The requested URL was rejected"],
        "cookie": ["BIGipServer", "TSe"],
        "status": [403, 406],
        "bypass_hint": "尝试分块传输或编码绕过",
        "block_signatures": ["BIG-IP", "ASM", "The requested URL was rejected"],
        "recommended_strategies": ["BP-F5-1", "BP-F5-2", "BP-F5-3"],
    },
    # D15：Akamai
    "akamai": {
        "display": "Akamai",
        "headers": ["AkamaiGHost", "X-Akamai-Transformed", "Server: AkamaiGHost"],
        "body": ["Akamai", "Access Denied", "Reference ID"],
        "cookie": ["AKA_A2", "akamai"],
        "status": [403],
        "bypass_hint": "尝试源站 IP 绕过或 HTTP/2 协议变形",
        "block_signatures": ["Akamai", "Access Denied", "akamai"],
        "recommended_strategies": ["BP-AK-1", "BP-AK-2", "BP-AK-3"],
    },
    # D15：Imperva Incapsula
    "imperva": {
        "display": "Imperva Incapsula",
        "headers": ["X-Iinfo", "Incapsula", "X-CDN: Imperva"],
        "body": ["Incapsula", "Incident ID", "Powered by Incapsula"],
        "cookie": ["incap_ses", "visid_incap"],
        "status": [403, 503],
        "bypass_hint": "尝试源站 IP 绕过或 cookie 变形",
        "block_signatures": ["Incapsula", "Incident ID", "Powered by Incapsula"],
        "recommended_strategies": ["BP-IM-1", "BP-IM-2", "BP-IM-3"],
    },
}


def get_waf_names():
    """返回所有已注册 WAF 标识列表"""
    return list(WAF_FEATURES.keys())


def is_waf_blocked(waf_type: str, response_text: str = "", status_code: int = 0) -> bool:
    """判断响应是否被 WAF 拦截（区分"真 SAFE"和"被拦假 SAFE"）

    Args:
        waf_type: WAF 标识
        response_text: 响应体文本
        status_code: HTTP 状态码

    Returns:
        True 表示被 WAF 拦截，False 表示真 SAFE
    """
    waf = WAF_FEATURES.get(waf_type, {})
    signatures = waf.get("block_signatures", [])
    # 状态码命中拦截码
    if status_code and status_code in waf.get("status", []):
        return True
    # 响应体含拦截特征
    if response_text:
        text_lower = response_text.lower()
        for sig in signatures:
            if sig.lower() in text_lower:
                return True
    return False
