# E8：AI 报告解读（--ai-report）
#
# 设计目标：扫描报告数据全（fix_detail/reproduce/CVSS/合规）但需人工整理，
# 用 LLM 自动生成漏洞分析摘要 + 修复优先级，直接提升报告交付价值。
#
# 实现：
#   1. --ai-report zh|en 在 render_all 后生成 report.analysis.<lang>.md
#      + HTML 报告内嵌「AI 分析」区块
#   2. LLM 优先（复用 lib/ai_generator 的 OpenAI 兼容客户端）
#   3. 无 Key 降级：模板化摘要（按严重度分组 + fix_detail 首行 + 复现命令清单）
#
# 安全：测试全部 mock，不真实调用外部 API；AI 分析标注「由 AI 生成，供参考」。
import json
import os
from typing import Dict, List

from common.logger import get_logger
from common.models import SEVERITY_CN, STATUS_CONFIRMED

# 与 ai_generator 共用 LLM 配置
from lib.ai_generator import AI_API_KEY, AI_BASE_URL, AI_MODEL, _llm_complete

logger = get_logger(__name__)

_ANALYSIS_PROMPT = """你是资深安全分析师。根据 Ruoyi-Scan 的扫描 JSON 报告，输出一份简洁的中文/英文
漏洞分析摘要，包含：
1. 总体结论（目标风险等级、漏洞数量、最紧急问题）
2. 高危漏洞逐个分析（漏洞名、影响、利用条件、修复优先级）
3. 修复优先级排序（按 CVSS × 可利用性）
4. 合规缺口（等保/OWASP 映射）

格式要求：Markdown，简洁分节，避免空话。只输出分析正文。"""


def _build_prompt(report_dict: dict, lang: str) -> str:
    """从 JSON 报告字典构建 LLM 提示词"""
    # 只把已确认漏洞喂给 LLM，避免误报/未确认项污染分析结论
    vulns = [r for r in report_dict.get("results", []) if r.get("status") == STATUS_CONFIRMED]
    summary = {
        "target": report_dict.get("target", ""),
        "scan_time": report_dict.get("scan_time", ""),
        "fingerprint": report_dict.get("fingerprint", {}),
        "risk_distribution": report_dict.get("risk_distribution", {}),
        "vuln_count": report_dict.get("vuln_count", 0),
        "vulns": [
            {
                "name": v.get("name"),
                "severity": v.get("severity"),
                "url": v.get("url"),
                "cve": v.get("cve"),
                "cvss_score": v.get("cvss_score"),
                "compliance": v.get("compliance"),
                # 截断长字段：控制 prompt token 消耗，首段即含关键信息
                "fix_detail": (v.get("fix_detail") or "")[:500],
                "reproduce": (v.get("reproduce") or "")[:300],
            }
            for v in vulns
        ],
    }
    return "%s\n\n语言: %s\n\n扫描报告 JSON:\n%s" % (
        _ANALYSIS_PROMPT,
        "zh" if lang == "zh" else "en",
        json.dumps(summary, ensure_ascii=False, indent=2),
    )


def _template_summary(report_dict: dict, lang: str) -> str:
    """降级模式：模板化摘要（无 LLM，纯数据整理）"""
    zh = lang == "zh"
    lines = []
    lines.append("# %s" % ("AI 分析（模板模式）" if zh else "AI Analysis (Template Mode)"))
    lines.append("")
    lines.append(
        "> %s"
        % (
            "由 Ruoyi-Scan 模板化生成（未配置 LLM API Key）。"
            if zh
            else "Generated by Ruoyi-Scan template (no LLM API Key configured)."
        )
    )
    dist = report_dict.get("risk_distribution", {})
    lines.append("")
    lines.append("## %s" % ("总体结论" if zh else "Summary"))
    lines.append(
        "%s %d（%s 高 / %d 中 / %d 低）"
        % (
            "确认漏洞总数：" if zh else "Confirmed vulns:",
            dist.get("total", 0),
            dist.get("high", 0),
            dist.get("medium", 0),
            dist.get("low", 0),
        )
    )
    confirmed = [r for r in report_dict.get("results", []) if r.get("status") == STATUS_CONFIRMED]
    confirmed_sorted = sorted(
        confirmed,
        # 排序：中文严重度升序优先，cvss_score 取负实现同级别内降序
        key=lambda r: (SEVERITY_CN.get(r.get("severity", ""), ""), -float(r.get("cvss_score", 0) or 0)),
    )
    if confirmed_sorted:
        lines.append("")
        lines.append("## %s" % ("高危漏洞 TOP3" if zh else "Top 3 Critical Findings"))
        for v in confirmed_sorted[:3]:
            sev = SEVERITY_CN.get(v.get("severity", ""), v.get("severity", ""))
            lines.append("- **[%s]** %s（%s）" % (sev, v.get("name", ""), v.get("url", "")))
            fix = v.get("fix") or v.get("fix_detail", "")
            if fix:
                # 多行修复建议只取首行，控制报告行宽并聚焦核心动作
                lines.append("  - %s: %s" % ("修复" if zh else "Fix", fix.splitlines()[0][:120]))
            repro = v.get("reproduce", "")
            if repro:
                lines.append("  - %s: %s" % ("复现" if zh else "Reproduce", repro.splitlines()[0][:120]))
    # 合规缺口
    compliance_map: Dict[str, List[str]] = {}
    for v in confirmed:
        for std, clause in (v.get("compliance") or {}).items():
            key = "%s:%s" % (std, clause)
            compliance_map.setdefault(key, []).append(v.get("name", ""))
    if compliance_map:
        lines.append("")
        lines.append("## %s" % ("合规缺口" if zh else "Compliance Gaps"))
        for key, names in sorted(compliance_map.items()):
            lines.append("- **%s**: %s" % (key, ", ".join(names[:5])))
    lines.append("")
    lines.append("---")
    lines.append(
        "*%s*"
        % (
            "AI 分析由模板生成，建议配置 LLM API Key 获得深度分析。"
            if zh
            else "Generated by template; configure LLM API key for deeper analysis."
        )
    )
    return "\n".join(lines)


def generate_analysis(
    report_dict: dict,
    lang: str = "zh",
    api_key: str = "",
    model: str = AI_MODEL,
    base_url: str = AI_BASE_URL,
) -> str:
    """生成漏洞分析摘要（LLM 优先，无 Key 降级模板）

    Args:
        report_dict: 扫描报告字典（ReportBuilder.to_dict()）
        lang: zh/en
        api_key: LLM API Key（空则降级模板）
        model: LLM 模型
        base_url: LLM API 地址

    Returns:
        分析 Markdown 文本
    """
    api_key = api_key or AI_API_KEY
    if api_key:
        try:
            messages = [
                {"role": "system", "content": _ANALYSIS_PROMPT},
                {"role": "user", "content": _build_prompt(report_dict, lang)},
            ]
            return _llm_complete(messages, model=model, api_key=api_key, base_url=base_url)
        except ValueError as e:
            logger.debug("AI 分析调用失败，降级模板: %s", e)
    return _template_summary(report_dict, lang)


def run_ai_report_mode(report_dir: str, report_dict: dict, lang: str = "zh") -> str:
    """--ai-report 入口：生成分析 md + 返回文件路径

    Args:
        report_dir: 报告输出目录
        report_dict: 扫描报告字典
        lang: zh/en

    Returns:
        分析文件路径
    """
    analysis = generate_analysis(report_dict, lang=lang)
    out_path = os.path.join(report_dir, "report.analysis.%s.md" % lang)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(analysis)
    return out_path
